routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::middleware('auth')->name('backend.')->prefix('backend')->group(function(){
    Route::get('category/trash', [\App\Http\Controllers\Backend\CategoryController::class, 'trash'])->name('category.trash');
    Route::get('category/restore/{id}', [\App\Http\Controllers\Backend\CategoryController::class, 'restore'])->name('category.restore');
    Route::delete('category/force_delete/{id}', [\App\Http\Controllers\Backend\CategoryController::class, 'forceDelete'])->name('category.force_delete');


    Route::get('category/create', [\App\Http\Controllers\Backend\CategoryController::class, 'create'])->name('category.create');
    Route::get('category', [\App\Http\Controllers\Backend\CategoryController::class, 'index'])->name('category.index');
    Route::post('category', [\App\Http\Controllers\Backend\CategoryController::class, 'store'])->name('category.store');
    Route::get('category/{id}', [\App\Http\Controllers\Backend\CategoryController::class, 'show'])->name('category.show');
    Route::delete('category/{id}', [\App\Http\Controllers\Backend\CategoryController::class, 'destroy'])->name('category.destroy');
    Route::get('category/{id}/edit', [\App\Http\Controllers\Backend\CategoryController::class, 'edit'])->name('category.edit');
    Route::put('category/{id}', [\App\Http\Controllers\Backend\CategoryController::class, 'update'])->name('category.update');


    Route::get('subcategory/trash', [\App\Http\Controllers\Backend\SubcategoryController::class, 'trash'])->name('subcategory.trash');
    Route::get('subcategory/restore/{id}', [\App\Http\Controllers\Backend\SubcategoryController::class, 'restore'])->name('subcategory.restore');
    Route::delete('subcategory/force_delete/{id}', [\App\Http\Controllers\Backend\SubcategoryController::class, 'forceDelete'])->name('subcategory.force_delete');

    Route::get('subcategory/create', [\App\Http\Controllers\Backend\SubcategoryController::class, 'create'])->name('subcategory.create');
    Route::get('subcategory', [\App\Http\Controllers\Backend\SubcategoryController::class, 'index'])->name('subcategory.index');
    Route::post('subcategory', [\App\Http\Controllers\Backend\SubcategoryController::class, 'store'])->name('subcategory.store');
    Route::get('subcategory/{id}', [\App\Http\Controllers\Backend\SubcategoryController::class, 'show'])->name('subcategory.show');
    Route::delete('subcategory/{id}', [\App\Http\Controllers\Backend\SubcategoryController::class, 'destroy'])->name('subcategory.destroy');
    Route::get('subcategory/{id}/edit', [\App\Http\Controllers\Backend\SubcategoryController::class, 'edit'])->name('subcategory.edit');
    Route::put('subcategory/{id}', [\App\Http\Controllers\Backend\SubcategoryController::class, 'update'])->name('subcategory.update');
});

app/Models/Subcategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Subcategory extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'subcategories';

    protected $fillable = ['category_id','title','rank','image','description','slug','meta_keyword','meta_description','created_by','updated_by','status'];
}

app/Http/Controllers/Backend/BackendBaseController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BackendBaseController extends Controller
{
    protected function  __loadDataToView($viewPath){
        view()->composer($viewPath, function ($view) {
            $view->with('base_route', $this->base_route);
            $view->with('base_view', $this->base_view);
            $view->with('module', $this->module);
            $view->with('folder', $this->folder);
        });
       return $viewPath;
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends BackendBaseController
{
    public $base_view = 'backend.category.';
    public $base_route = 'backend.category.';
    public $module = 'Category';
    public $folder = 'category';

    public function __construct(){
        $this->model = new Category();
    }
    function create(){
        return view($this->__loadDataToView($this->base_view . 'create'));
    }

    function index()
    {
        $data['records'] = $this->model->paginate(2);
        return view($this->__loadDataToView($this->base_view .'index'),compact('data'));
    }

    function store(CategoryRequest $request)
    {
        if ($request->hasFile('image_file')){
            $file = $request->file('image_file');
            $iname = uniqid() . '_' . $file->getClientOriginalName();
            $file->move('images/category/',$iname);
            $request->request->add(['image' => $iname]);
        }
        $request->request->add(['created_by' => auth()->user()->id]);
        $this->model->create($request->all());
        return redirect()->route($this->base_route . 'index');
    }

    function  show($id){
       $data['record'] =  $this->model->find($id);
       if (!$data['record']){
           return redirect()->route($this->base_route .'index');
       }
       return view($this->__loadDataToView($this->base_view . 'show'),compact('data'));
    }

    function destroy($id){
       $data =  $this->model->find($id);
       $data->delete();
        return redirect()->route($this->base_route .'index');
    }

    function edit($id){
        $data['record'] =  $this->model->find($id);
        return view($this->__loadDataToView($this->base_view .'edit'),compact('data'));
    }

    function update(CategoryRequest $request,$id)
    {
        $data = $this->model->find($id);
        if ($request->hasFile('image_file')){
            $file = $request->file('image_file');
            $iname = uniqid() . '_' . $file->getClientOriginalName();
            $file->move('images/category/',$iname);
            $request->request->add(['image' => $iname]);
        }
        $request->request->add(['updated_by' => auth()->user()->id]);
        $data->update($request->all());
        return redirect()->route($this->base_route .'index');
    }

    function trash()
    {
        $data = $this->model->onlyTrashed()->get();
        return view($this->__loadDataToView($this->base_view .'trash'),compact('data'));
    }

    function restore($id)
    {
        $data = $this->model->onlyTrashed()->find($id)->restore();
        return redirect()->route($this->base_route .'trash');
    }

    function forceDelete($id)
    {
        $data = $this->model->onlyTrashed()->find($id)->forceDelete();
        return redirect()->route($this->base_route .'trash');
    }
}

app/Http/Controllers/Backend/SubcategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Subcategory;
use Illuminate\Http\Request;

class SubcategoryController extends BackendBaseController
{
    public $base_view = 'backend.subcategory.';
    public $base_route = 'backend.subcategory.';
    public $module = 'SubCategory';
    public $folder = 'Subcategory';

    public function __construct(){
        $this->model = new Subcategory();
    }
    function create(){
        $data['categories'] = Category::select('title','id')->get();
        return view($this->__loadDataToView($this->base_view . 'create'),compact('data'));
    }

    function index()
    {
        $data['records'] = $this->model->all();
        return view($this->__loadDataToView($this->base_view .'index'),compact('data'));
    }

    function store(Request $request)
    {
        $validated = $request->validate([
            'category_id' => 'required',
            'title' => 'required|max:255',
            'slug' => 'required',
            'rank' => 'required|integer',
            'image_file' => 'required|mimes:jpg,bmp,png'
        ]);
        if ($request->hasFile('image_file')){
            $file = $request->file('image_file');
            $iname = uniqid() . '_' . $file->getClientOriginalName();
            $file->move('images/subcategory/',$iname);
            $request->request->add(['image' => $iname]);
        }
        $request->request->add(['created_by' => auth()->user()->id]);
        $this->model->create($request->all());
        return redirect()->route($this->base_route . 'index');
    }

    function  show($id){
       $data['record'] =  $this->model->find($id);
       if (!$data['record']){
           return redirect()->route($this->base_route .'index');
       }
       return view($this->__loadDataToView($this->base_view . 'show'),compact('data'));
    }

    function destroy($id){
       $data =  $this->model->find($id);
       $data->delete();
        return redirect()->route($this->base_route .'index');
    }

    function edit($id){
        $data['record'] =  $this->model->find($id);
        return view($this->__loadDataToView($this->base_view .'edit'),compact('data'));
    }

    function update(Request $request,$id)
    {
        $data = $this->model->find($id);
        $validated = $request->validate([
            'title' => 'required|max:255',
            'slug' => 'required',
            'rank' => 'required|integer'
        ]);
        if ($request->hasFile('image_file')){
            $file = $request->file('image_file');
            $iname = uniqid() . '_' . $file->getClientOriginalName();
            $file->move('images/category/',$iname);
            $request->request->add(['image' => $iname]);
        }
        $request->request->add(['updated_by' => auth()->user()->id]);
        $data->update($request->all());
        return redirect()->route($this->base_route .'index');
    }

    function trash()
    {
        $data = $this->model->onlyTrashed()->get();
        return view($this->__loadDataToView($this->base_view .'trash'),compact('data'));
    }

    function restore($id)
    {
        $data = $this->model->onlyTrashed()->find($id)->restore();
        return redirect()->route($this->base_route .'trash');
    }

    function forceDelete($id)
    {
        $data = $this->model->onlyTrashed()->find($id)->forceDelete();
        return redirect()->route($this->base_route .'trash');
    }
}

resources/views/backend/subcategory/create.blade.php
@extends('layouts.backend')
@section('title',$module . ' Create')
@section('breadcrumb')
    <div class="col-sm-6">
        <h1>{{$module}} Management</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item ">{{$module}}</li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </div>
@endsection
@section('content')
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Create {{$module}}</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>

            <div class="card-body">
                <form action="{{route($base_route . 'store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="category_id">Category</label>
                        <select class="form-control" name="category_id" id="category_id">
                            <option value="">Select Category</option>
                            @foreach($data['categories'] as $cat)
                                <option value="{{$cat->id}}">{{$cat->title}}</option>
                            @endforeach
                        </select>
                        @include('backend.includes.error_display',['field' => 'category_id'])
                    </div>
                    <div class="form-group">
                        <label for="">Title</label>
                        <input type="text" class="form-control" name="title">
                        @include('backend.includes.error_display',['field' => 'title'])
                    </div>
                    <div class="form-group">
                        <label for="">Slug</label>
                        <input type="text" class="form-control" name="slug">
                        @include('backend.includes.error_display',['field' => 'slug'])
                    </div>
                    <div class="form-group">
                        <label for="">Rank</label>
                        <input type="text" class="form-control" name="rank">
                        @include('backend.includes.error_display',['field' => 'rank'])
                    </div>
                    <div class="form-group">
                        <label for="">Image</label>
                        <input type="file" class="form-control" name="image_file" accept="image/*" onchange="loadFile(event)">
                        @include('backend.includes.error_display',['field' => 'image_file'])

                        <img id="output" height="100px"/>
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea name="description" id="" class="form-control" cols="30" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Meta Description</label>
                        <textarea name="meta_description" id="" class="form-control" cols="30" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Meta Keyword</label>
                        <textarea name="meta_keyword" id="" class="form-control" cols="30" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Status</label><br>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" value="1" name="status" id="flexRadioDefault1">
                            <label class="form-check-label" for="flexRadioDefault1">
                               Active
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="status" value="0" id="flexRadioDefault2" checked>
                            <label class="form-check-label" for="flexRadioDefault2">
                                De Active
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Save {{$module}}">
                        <input type="reset" class="btn btn-danger" value="Clear">
                    </div>
                </form>
            </div>
            <!-- /.card-body -->

            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@endsection
@section('js')
    <script>
        var loadFile = function(event) {
            var output = document.getElementById('output');
            output.src = URL.createObjectURL(event.target.files[0]);
            output.onload = function() {
                URL.revokeObjectURL(output.src) // free memory
            }
        };
    </script>
@endsection

resources/views/backend/subcategory/edit.blade.php
@extends('layouts.backend')
@section('title','Category Create')
@section('breadcrumb')
    <div class="col-sm-6">
        <h1>Category Management</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item ">Category</li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
    </div>
@endsection
@section('content')
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Edit Category</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>

            <div class="card-body">
                <form action="{{route('backend.category.update',$data['record']->id)}}" method="post" enctype="multipart/form-data">
                    <input  type="hidden" name="_method" value="put">

                    @csrf
                    <div class="form-group">
                        <label for="">Title</label>
                        <input type="text" class="form-control" name="title" value="{{$data['record']->title}}">
                        @include('backend.includes.error_display',['field' => 'title'])

                    </div>
                    <div class="form-group">
                        <label for="">Slug</label>
                        <input type="text" class="form-control" name="slug" value="{{$data['record']->slug}}">
                        @include('backend.includes.error_display',['field' => 'slug'])

                    </div>
                    <div class="form-group">
                        <label for="">Rank</label>
                        <input type="text" class="form-control" name="rank" value="{{$data['record']->rank}}">
                        @include('backend.includes.error_display',['field' => 'rank'])
                    </div>
                    <div class="form-group">
                        <label for="">Image</label>
                        <input type="file" class="form-control" name="image_file" accept="image/*" onchange="loadFile(event)">
                        @include('backend.includes.error_display',['field' => 'image_file'])

                        <img id="output" height="100px"/>
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea name="description" id="" class="form-control" cols="30" rows="3">{{$data['record']->description}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Meta Description</label>
                        <textarea name="meta_description" id="" class="form-control" cols="30" rows="3">{{$data['record']->meta_description}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Meta Keyword</label>
                        <textarea name="meta_keyword" id="" class="form-control" cols="30" rows="3">{{$data['record']->meta_keyword}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Status</label><br>
                        @if($data['record']->status == 1)
                        <div class="form-check">
                            <input class="form-check-input" type="radio" value="1" name="status" id="flexRadioDefault1" checked>
                            <label class="form-check-label" for="flexRadioDefault1">
                               Active
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="status" value="0" id="flexRadioDefault2">
                            <label class="form-check-label" for="flexRadioDefault2">
                                De Active
                            </label>
                        </div>
                        @endif
                        @if($data['record']->status == 0)
                            <div class="form-check">
                                <input class="form-check-input" type="radio" value="1" name="status" id="flexRadioDefault1">
                                <label class="form-check-label" for="flexRadioDefault1">
                                    Active
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="status" value="0" id="flexRadioDefault2" checked>
                                <label class="form-check-label" for="flexRadioDefault2">
                                    De Active
                                </label>
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Save Category">
                        <input type="reset" class="btn btn-danger" value="Clear">
                    </div>
                </form>
            </div>
            <!-- /.card-body -->

            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@endsection
@section('js')
    <script>
        var loadFile = function(event) {
            var output = document.getElementById('output');
            output.src = URL.createObjectURL(event.target.files[0]);
            output.onload = function() {
                URL.revokeObjectURL(output.src) // free memory
            }
        };
    </script>
    @endsection

resources/views/backend/subcategory/index.blade.php
@extends('layouts.backend')
@section('title',$module . ' List')
@section('breadcrumb')
    <div class="col-sm-6">
        <h1>{{$module}} Management</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item ">{{$module}}</li>
            <li class="breadcrumb-item active">List</li>
        </ol>
    </div>
@endsection
@section('content')
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">List {{$module}}</h3>
                <div class="card-tools">
                    <a href="{{route($base_route . 'trash')}}" class="btn btn-danger">Trash</a>
                    <a href="{{route($base_route . 'create')}}" class="btn btn-info">Create</a>
                </div>
            </div>
            <div class="card-body table-responsive">
                <table class="table table-bordered">
                    <tr>
                        <th>SN</th>
                        <th>Title</th>
                        <th>Image</th>
                        <th>Rank</th>
                        <th>Action</th>
                    </tr>
                    @foreach($data['records'] as $record)
                    <tr>
                        <td>{{$loop->index +1}}</td>
                        <td>{{$record->title}}</td>
                        <td><img src="{{asset('images/' .$folder.'/' . $record->image)}}" alt="" width="100"></td>
                        <td>{{$record->rank}}</td>
                        <td>
                            <a href="{{route($base_route . 'show',$record->id)}}" class="btn btn-info">View</a>
                            <a href="{{route($base_route . 'edit',$record->id)}}" class="btn btn-warning">Edit</a>
                            <form method="post" action="{{route($base_route . 'destroy',$record->id)}}" style="display: inline-block;" >
                                <input  type="hidden" name="_method" value="delete">
                                @csrf
                                <input type="submit" class="btn btn-danger" value="Delete">
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                Footer
            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
@endsection

resources/views/backend/subcategory/show.blade.php
@extends('layouts.backend')
@section('title','Category List')
@section('breadcrumb')
    <div class="col-sm-6">
        <h1>Category Management</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item ">Category</li>
            <li class="breadcrumb-item active">List</li>
        </ol>
    </div>
@endsection
@section('content')
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">List Category</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <tr>
                        <th>Title</th>
                        <td>{{$data['record']->title}}</td>
                    </tr>
                    <tr>
                        <th>Rank</th>
                        <td>{{$data['record']->rank}}</td>
                    </tr>
                    <tr>
                        <th>Slug</th>
                        <td>{{$data['record']->slug}}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{$data['record']->description}}</td>
                    </tr>
                    <tr>
                        <th>Image</th>
                        <td><img src="{{asset('images/category/' . $data['record']->image)}}" alt="" width="50%"></td>
                    </tr>
                </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                Footer
            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@endsection

resources/views/backend/subcategory/trash.blade.php
@extends('layouts.backend')
@section('title','Category List')
@section('breadcrumb')
    <div class="col-sm-6">
        <h1>Category Management</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item ">Category</li>
            <li class="breadcrumb-item active">Trash</li>
        </ol>
    </div>
@endsection
@section('content')
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">List Category Trash
                    <a href="{{route('backend.category.index')}}" class="btn btn-success">List</a>
                </h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <tr>
                        <th>SN</th>
                        <th>Title</th>
                        <th>Image</th>
                        <th>Rank</th>
                        <th>Action</th>
                    </tr>
                    @foreach($data as $category)
                    <tr>
                        <td>{{$loop->index +1}}</td>
                        <td>{{$category->title}}</td>
                        <td><img src="{{asset('images/category/' . $category->image)}}" alt="" width="100"></td>
                        <td>{{$category->rank}}</td>
                        <td>
                            <a href="{{route('backend.category.restore',$category->id)}}" class="btn btn-info">Restore</a>
                            <form method="post" action="{{route('backend.category.force_delete',$category->id)}}" >
                                <input  type="hidden" name="_method" value="delete">
                                @csrf
                                <input type="submit" class="btn btn-danger" value="Delete">
                            </form>


                        </td>
                    </tr>
                    @endforeach
                </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                Footer
            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@endsection